/**
 * Zentrale Datendefinitionen für das Cybersecurity Dashboard.
 * Tool-Katalog (118 Tools), Kategorien, Ausführungsmodi und operative Konfiguration.
 */

export type ToolCategory = "osint" | "pentest" | "recon" | "cloud" | "forensics" | "binary";
export type ToolRisk = "passiv" | "kontrolliert" | "aktiv";
export type ExecutionMode = "web-integrated" | "command-reference" | "external";
export type JobStatus = "idle" | "scanning" | "success" | "error";

export interface ToolDefinition {
  id: string;
  name: string;
  category: ToolCategory;
  risk: ToolRisk;
  description: string; // Kurz, max 60 Zeichen
  executionMode: ExecutionMode;
  inputFields: Array<{
    name: string;
    label: string;
    type: "text" | "textarea" | "select";
    placeholder?: string;
    options?: string[];
  }>;
  commandTemplate?: string; // Für command-reference Mode
}

export const toolCatalog: ToolDefinition[] = [
  // ========== OSINT TOOLS (13 Tools) ==========
  {
    id: "amass",
    name: "Amass",
    category: "osint",
    risk: "passiv",
    description: "Advanced subdomain enumeration and OSINT gathering",
    executionMode: "command-reference",
    inputFields: [{ name: "domain", label: "Domain", type: "text" }],
    commandTemplate: "amass enum -d {{domain}}",
  },
  {
    id: "subfinder",
    name: "Subfinder",
    category: "osint",
    risk: "passiv",
    description: "Fast passive subdomain discovery",
    executionMode: "command-reference",
    inputFields: [{ name: "domain", label: "Domain", type: "text" }],
    commandTemplate: "subfinder -d {{domain}}",
  },
  {
    id: "fierce",
    name: "Fierce",
    category: "osint",
    risk: "passiv",
    description: "DNS reconnaissance and zone transfer testing",
    executionMode: "command-reference",
    inputFields: [{ name: "domain", label: "Domain", type: "text" }],
    commandTemplate: "fierce --domain {{domain}}",
  },
  {
    id: "dnsenum",
    name: "DNSEnum",
    category: "osint",
    risk: "passiv",
    description: "DNS information gathering and subdomain brute forcing",
    executionMode: "command-reference",
    inputFields: [{ name: "domain", label: "Domain", type: "text" }],
    commandTemplate: "dnsenum {{domain}}",
  },
  {
    id: "theharvester",
    name: "theHarvester",
    category: "osint",
    risk: "passiv",
    description: "Email and subdomain harvesting from multiple sources",
    executionMode: "command-reference",
    inputFields: [
      { name: "domain", label: "Domain", type: "text" },
      { name: "source", label: "Source", type: "select", options: ["google", "bing", "linkedin"] },
    ],
    commandTemplate: "theHarvester -d {{domain}} -b {{source}}",
  },
  {
    id: "sherlock",
    name: "Sherlock",
    category: "osint",
    risk: "passiv",
    description: "Username search across social networks",
    executionMode: "web-integrated",
    inputFields: [{ name: "username", label: "Username", type: "text" }],
  },
  {
    id: "social-analyzer",
    name: "Social Analyzer",
    category: "osint",
    risk: "passiv",
    description: "Profile and activity analysis across platforms",
    executionMode: "web-integrated",
    inputFields: [{ name: "profile", label: "Profile/Handle", type: "text" }],
  },
  {
    id: "recon-ng",
    name: "Recon-ng",
    category: "osint",
    risk: "passiv",
    description: "Web reconnaissance framework",
    executionMode: "web-integrated",
    inputFields: [{ name: "target", label: "Target Domain", type: "text" }],
  },
  {
    id: "maltego",
    name: "Maltego",
    category: "osint",
    risk: "passiv",
    description: "Visual data correlation and transformation",
    executionMode: "web-integrated",
    inputFields: [{ name: "entity", label: "Entity", type: "text" }],
  },
  {
    id: "spiderfoot",
    name: "SpiderFoot",
    category: "osint",
    risk: "passiv",
    description: "Automated OSINT automation framework",
    executionMode: "web-integrated",
    inputFields: [{ name: "target", label: "Target", type: "text" }],
  },
  {
    id: "shodan-cli",
    name: "Shodan CLI",
    category: "osint",
    risk: "passiv",
    description: "IoT and network device search",
    executionMode: "web-integrated",
    inputFields: [{ name: "query", label: "Search Query", type: "text" }],
  },
  {
    id: "censys-cli",
    name: "Censys CLI",
    category: "osint",
    risk: "passiv",
    description: "Certificate and host data discovery",
    executionMode: "web-integrated",
    inputFields: [{ name: "query", label: "Search Query", type: "text" }],
  },
  {
    id: "have-i-been-pwned",
    name: "Have I Been Pwned",
    category: "osint",
    risk: "passiv",
    description: "Breach database search and credential verification",
    executionMode: "web-integrated",
    inputFields: [{ name: "email", label: "Email Address", type: "text" }],
  },

  // ========== NETWORK RECONNAISSANCE TOOLS (10 Tools) ==========
  {
    id: "nmap",
    name: "Nmap",
    category: "recon",
    risk: "kontrolliert",
    description: "Port scanning and host discovery",
    executionMode: "command-reference",
    inputFields: [{ name: "target", label: "Target IP/Host", type: "text" }],
    commandTemplate: "nmap -sV {{target}}",
  },
  {
    id: "rustscan",
    name: "Rustscan",
    category: "recon",
    risk: "kontrolliert",
    description: "Ultra-fast port scanner with intelligent rate limiting",
    executionMode: "command-reference",
    inputFields: [{ name: "target", label: "Target IP/Range", type: "text" }],
    commandTemplate: "rustscan -a {{target}}",
  },
  {
    id: "masscan",
    name: "Masscan",
    category: "recon",
    risk: "kontrolliert",
    description: "High-speed Internet-scale port scanning",
    executionMode: "web-integrated",
    inputFields: [{ name: "target", label: "Target IP/Range", type: "text" }],
  },
  {
    id: "autorecon",
    name: "AutoRecon",
    category: "recon",
    risk: "kontrolliert",
    description: "Comprehensive automated reconnaissance",
    executionMode: "command-reference",
    inputFields: [{ name: "target", label: "Target", type: "text" }],
    commandTemplate: "autorecon {{target}}",
  },
  {
    id: "nbtscan",
    name: "NBTScan",
    category: "recon",
    risk: "kontrolliert",
    description: "NetBIOS name scanning and enumeration",
    executionMode: "command-reference",
    inputFields: [{ name: "target", label: "Target IP/Range", type: "text" }],
    commandTemplate: "nbtscan {{target}}",
  },
  {
    id: "arp-scan",
    name: "ARP-Scan",
    category: "recon",
    risk: "kontrolliert",
    description: "Network discovery using ARP requests",
    executionMode: "command-reference",
    inputFields: [{ name: "interface", label: "Network Interface", type: "text" }],
    commandTemplate: "arp-scan -l",
  },
  {
    id: "responder",
    name: "Responder",
    category: "recon",
    risk: "aktiv",
    description: "LLMNR/NBT-NS poisoner for credential harvesting",
    executionMode: "external",
    inputFields: [{ name: "interface", label: "Interface", type: "text" }],
  },
  {
    id: "nxc",
    name: "NetExec (NXC)",
    category: "recon",
    risk: "aktiv",
    description: "Network service exploitation framework",
    executionMode: "external",
    inputFields: [{ name: "target", label: "Target", type: "text" }],
  },
  {
    id: "enum4linux-ng",
    name: "Enum4linux-ng",
    category: "recon",
    risk: "kontrolliert",
    description: "Advanced SMB enumeration with enhanced logging",
    executionMode: "web-integrated",
    inputFields: [{ name: "target", label: "Target IP", type: "text" }],
  },
  {
    id: "enum4linux",
    name: "Enum4linux",
    category: "recon",
    risk: "kontrolliert",
    description: "SMB enumeration with user and share discovery",
    executionMode: "web-integrated",
    inputFields: [{ name: "target", label: "Target IP", type: "text" }],
  },

  // ========== WEB APPLICATION SECURITY TOOLS (18 Tools) ==========
  {
    id: "gobuster",
    name: "Gobuster",
    category: "pentest",
    risk: "kontrolliert",
    description: "Directory, file, and DNS enumeration",
    executionMode: "command-reference",
    inputFields: [{ name: "url", label: "Target URL", type: "text" }],
    commandTemplate: "gobuster dir -u {{url}} -w wordlist.txt",
  },
  {
    id: "feroxbuster",
    name: "Feroxbuster",
    category: "pentest",
    risk: "kontrolliert",
    description: "Recursive content discovery with intelligent filtering",
    executionMode: "command-reference",
    inputFields: [{ name: "url", label: "Target URL", type: "text" }],
    commandTemplate: "feroxbuster -u {{url}}",
  },
  {
    id: "dirsearch",
    name: "Dirsearch",
    category: "pentest",
    risk: "kontrolliert",
    description: "Advanced directory and file discovery",
    executionMode: "command-reference",
    inputFields: [{ name: "url", label: "Target URL", type: "text" }],
    commandTemplate: "dirsearch -u {{url}}",
  },
  {
    id: "ffuf",
    name: "FFuf",
    category: "pentest",
    risk: "kontrolliert",
    description: "Fast web fuzzer with advanced filtering",
    executionMode: "command-reference",
    inputFields: [{ name: "url", label: "Target URL", type: "text" }],
    commandTemplate: "ffuf -u {{url}}/FUZZ -w wordlist.txt",
  },
  {
    id: "dirb",
    name: "Dirb",
    category: "pentest",
    risk: "kontrolliert",
    description: "Comprehensive web content scanner",
    executionMode: "command-reference",
    inputFields: [{ name: "url", label: "Target URL", type: "text" }],
    commandTemplate: "dirb {{url}}",
  },
  {
    id: "httpx",
    name: "HTTPx",
    category: "pentest",
    risk: "passiv",
    description: "Fast HTTP probing and technology detection",
    executionMode: "command-reference",
    inputFields: [{ name: "input", label: "Host List", type: "textarea" }],
    commandTemplate: "httpx -l hosts.txt",
  },
  {
    id: "katana",
    name: "Katana",
    category: "pentest",
    risk: "kontrolliert",
    description: "Next-generation crawling and spidering",
    executionMode: "command-reference",
    inputFields: [{ name: "url", label: "Target URL", type: "text" }],
    commandTemplate: "katana -u {{url}}",
  },
  {
    id: "hakrawler",
    name: "Hakrawler",
    category: "pentest",
    risk: "passiv",
    description: "Fast web endpoint discovery and crawling",
    executionMode: "command-reference",
    inputFields: [{ name: "url", label: "Target URL", type: "text" }],
    commandTemplate: "hakrawler -u {{url}}",
  },
  {
    id: "gau",
    name: "GAU",
    category: "pentest",
    risk: "passiv",
    description: "Get All URLs from multiple sources",
    executionMode: "command-reference",
    inputFields: [{ name: "domain", label: "Domain", type: "text" }],
    commandTemplate: "gau {{domain}}",
  },
  {
    id: "waybackurls",
    name: "Waybackurls",
    category: "pentest",
    risk: "passiv",
    description: "Historical URL discovery from Wayback Machine",
    executionMode: "command-reference",
    inputFields: [{ name: "domain", label: "Domain", type: "text" }],
    commandTemplate: "waybackurls {{domain}}",
  },
  {
    id: "nuclei",
    name: "Nuclei",
    category: "pentest",
    risk: "kontrolliert",
    description: "Fast vulnerability scanner with 4000+ templates",
    executionMode: "command-reference",
    inputFields: [{ name: "url", label: "Target URL", type: "text" }],
    commandTemplate: "nuclei -u {{url}} -t cves/",
  },
  {
    id: "nikto",
    name: "Nikto",
    category: "pentest",
    risk: "kontrolliert",
    description: "Web server vulnerability scanner",
    executionMode: "command-reference",
    inputFields: [{ name: "url", label: "Target URL", type: "text" }],
    commandTemplate: "nikto -h {{url}}",
  },
  {
    id: "sqlmap",
    name: "SQLMap",
    category: "pentest",
    risk: "kontrolliert",
    description: "Automatic SQL injection detection and exploitation",
    executionMode: "web-integrated",
    inputFields: [{ name: "url", label: "Target URL", type: "text" }],
  },
  {
    id: "wpscan",
    name: "WPScan",
    category: "pentest",
    risk: "kontrolliert",
    description: "WordPress security scanner",
    executionMode: "web-integrated",
    inputFields: [{ name: "url", label: "WordPress URL", type: "text" }],
  },
  {
    id: "arjun",
    name: "Arjun",
    category: "pentest",
    risk: "kontrolliert",
    description: "HTTP parameter discovery with intelligent fuzzing",
    executionMode: "command-reference",
    inputFields: [{ name: "url", label: "Target URL", type: "text" }],
    commandTemplate: "arjun -u {{url}}",
  },
  {
    id: "paramspider",
    name: "ParamSpider",
    category: "pentest",
    risk: "passiv",
    description: "Parameter mining from web archives",
    executionMode: "command-reference",
    inputFields: [{ name: "domain", label: "Domain", type: "text" }],
    commandTemplate: "paramspider -d {{domain}}",
  },
  {
    id: "dalfox",
    name: "Dalfox",
    category: "pentest",
    risk: "kontrolliert",
    description: "Advanced XSS vulnerability scanning",
    executionMode: "command-reference",
    inputFields: [{ name: "url", label: "Target URL", type: "text" }],
    commandTemplate: "dalfox url {{url}}",
  },
  {
    id: "wafw00f",
    name: "Wafw00f",
    category: "pentest",
    risk: "passiv",
    description: "Web application firewall fingerprinting",
    executionMode: "command-reference",
    inputFields: [{ name: "url", label: "Target URL", type: "text" }],
    commandTemplate: "wafw00f {{url}}",
  },

  // ========== VULNERABILITY SCANNING TOOLS (4 Tools) ==========
  {
    id: "graphql-scanner",
    name: "GraphQL Scanner",
    category: "pentest",
    risk: "kontrolliert",
    description: "GraphQL schema exploration and introspection testing",
    executionMode: "web-integrated",
    inputFields: [{ name: "endpoint", label: "GraphQL Endpoint", type: "text" }],
  },
  {
    id: "jwt-analyzer",
    name: "JWT Analyzer",
    category: "pentest",
    risk: "passiv",
    description: "JSON Web Token testing with algorithm confusion",
    executionMode: "web-integrated",
    inputFields: [{ name: "token", label: "JWT Token", type: "textarea" }],
  },
  {
    id: "testssl",
    name: "TestSSL",
    category: "pentest",
    risk: "passiv",
    description: "SSL/TLS configuration testing and vulnerability assessment",
    executionMode: "command-reference",
    inputFields: [{ name: "host", label: "Host:Port", type: "text" }],
    commandTemplate: "testssl.sh {{host}}",
  },
  {
    id: "sslscan",
    name: "SSLScan",
    category: "pentest",
    risk: "passiv",
    description: "SSL/TLS cipher suite enumeration",
    executionMode: "command-reference",
    inputFields: [{ name: "host", label: "Target Host", type: "text" }],
    commandTemplate: "sslscan {{host}}",
  },

  // ========== PASSWORD & AUTHENTICATION TOOLS (5 Tools) ==========
  {
    id: "hydra",
    name: "Hydra",
    category: "pentest",
    risk: "aktiv",
    description: "Brute-force login tester",
    executionMode: "command-reference",
    inputFields: [
      { name: "target", label: "Target Host", type: "text" },
      { name: "service", label: "Service", type: "select", options: ["ssh", "ftp", "http"] },
    ],
    commandTemplate: "hydra -l admin -P wordlist.txt {{target}} {{service}}",
  },
  {
    id: "john",
    name: "John the Ripper",
    category: "pentest",
    risk: "passiv",
    description: "Password hash cracker",
    executionMode: "command-reference",
    inputFields: [{ name: "hashfile", label: "Hash File", type: "text" }],
    commandTemplate: "john {{hashfile}}",
  },
  {
    id: "hashcat",
    name: "Hashcat",
    category: "pentest",
    risk: "passiv",
    description: "GPU-accelerated hash cracking",
    executionMode: "command-reference",
    inputFields: [{ name: "hashfile", label: "Hash File", type: "text" }],
    commandTemplate: "hashcat -m 0 {{hashfile}} wordlist.txt",
  },
  {
    id: "medusa",
    name: "Medusa",
    category: "pentest",
    risk: "aktiv",
    description: "Parallel network login auditor",
    executionMode: "command-reference",
    inputFields: [{ name: "target", label: "Target Host", type: "text" }],
    commandTemplate: "medusa -h {{target}} -U users.txt -P passwords.txt -M ssh",
  },
  {
    id: "patator",
    name: "Patator",
    category: "pentest",
    risk: "aktiv",
    description: "Multi-protocol brute force tool",
    executionMode: "command-reference",
    inputFields: [{ name: "target", label: "Target", type: "text" }],
    commandTemplate: "patator ssh_login host={{target}} user=FILE0 password=FILE1",
  },

  // ========== BINARY ANALYSIS & REVERSE ENGINEERING (13 Tools) ==========
  {
    id: "gdb",
    name: "GDB",
    category: "binary",
    risk: "passiv",
    description: "GNU Debugger for binary analysis",
    executionMode: "external",
    inputFields: [{ name: "binary", label: "Binary Path", type: "text" }],
  },
  {
    id: "radare2",
    name: "Radare2",
    category: "binary",
    risk: "passiv",
    description: "Reverse engineering framework",
    executionMode: "external",
    inputFields: [{ name: "binary", label: "Binary Path", type: "text" }],
  },
  {
    id: "binwalk",
    name: "Binwalk",
    category: "binary",
    risk: "passiv",
    description: "Firmware analysis and extraction",
    executionMode: "command-reference",
    inputFields: [{ name: "file", label: "File Path", type: "text" }],
    commandTemplate: "binwalk {{file}}",
  },
  {
    id: "ghidra",
    name: "Ghidra",
    category: "binary",
    risk: "passiv",
    description: "Software reverse engineering suite",
    executionMode: "external",
    inputFields: [{ name: "binary", label: "Binary Path", type: "text" }],
  },
  {
    id: "checksec",
    name: "Checksec",
    category: "binary",
    risk: "passiv",
    description: "Binary security properties checker",
    executionMode: "command-reference",
    inputFields: [{ name: "binary", label: "Binary Path", type: "text" }],
    commandTemplate: "checksec --file={{binary}}",
  },
  {
    id: "objdump",
    name: "Objdump",
    category: "binary",
    risk: "passiv",
    description: "Object file disassembler",
    executionMode: "command-reference",
    inputFields: [{ name: "binary", label: "Binary Path", type: "text" }],
    commandTemplate: "objdump -d {{binary}}",
  },
  {
    id: "strings",
    name: "Strings",
    category: "binary",
    risk: "passiv",
    description: "Extract printable strings from files",
    executionMode: "command-reference",
    inputFields: [{ name: "file", label: "File Path", type: "text" }],
    commandTemplate: "strings {{file}}",
  },
  {
    id: "pwntools",
    name: "Pwntools",
    category: "binary",
    risk: "passiv",
    description: "CTF and exploit development framework",
    executionMode: "external",
    inputFields: [{ name: "script", label: "Python Script", type: "textarea" }],
  },
  {
    id: "ropgadget",
    name: "ROPGadget",
    category: "binary",
    risk: "passiv",
    description: "ROP gadget finder and exploit generator",
    executionMode: "command-reference",
    inputFields: [{ name: "binary", label: "Binary Path", type: "text" }],
    commandTemplate: "ROPgadget --file {{binary}}",
  },
  {
    id: "one-gadget",
    name: "One Gadget",
    category: "binary",
    risk: "passiv",
    description: "One-shot libc ROP gadget finder",
    executionMode: "command-reference",
    inputFields: [{ name: "libc", label: "Libc Path", type: "text" }],
    commandTemplate: "one_gadget {{libc}}",
  },
  {
    id: "ropper",
    name: "Ropper",
    category: "binary",
    risk: "passiv",
    description: "ROP gadget search and binary information",
    executionMode: "command-reference",
    inputFields: [{ name: "binary", label: "Binary Path", type: "text" }],
    commandTemplate: "ropper --file {{binary}}",
  },
  {
    id: "angr",
    name: "Angr",
    category: "binary",
    risk: "passiv",
    description: "Binary analysis framework",
    executionMode: "external",
    inputFields: [{ name: "binary", label: "Binary Path", type: "text" }],
  },
  {
    id: "pwninit",
    name: "Pwninit",
    category: "binary",
    risk: "passiv",
    description: "CTF challenge environment setup",
    executionMode: "command-reference",
    inputFields: [{ name: "binary", label: "Binary Path", type: "text" }],
    commandTemplate: "pwninit --binary {{binary}}",
  },

  // ========== FORENSICS & STEGANOGRAPHY TOOLS (16 Tools) ==========
  {
    id: "volatility3",
    name: "Volatility3",
    category: "forensics",
    risk: "passiv",
    description: "Memory forensics analysis framework",
    executionMode: "command-reference",
    inputFields: [{ name: "dump", label: "Memory Dump", type: "text" }],
    commandTemplate: "vol -f {{dump}} windows.pslist",
  },
  {
    id: "steghide",
    name: "Steghide",
    category: "forensics",
    risk: "passiv",
    description: "Steganography hiding and extraction",
    executionMode: "command-reference",
    inputFields: [{ name: "file", label: "File Path", type: "text" }],
    commandTemplate: "steghide extract -sf {{file}}",
  },
  {
    id: "exiftool",
    name: "ExifTool",
    category: "forensics",
    risk: "passiv",
    description: "Metadata extraction from files",
    executionMode: "command-reference",
    inputFields: [{ name: "file", label: "File Path", type: "text" }],
    commandTemplate: "exiftool {{file}}",
  },
  {
    id: "foremost",
    name: "Foremost",
    category: "forensics",
    risk: "passiv",
    description: "File recovery and data carving",
    executionMode: "command-reference",
    inputFields: [{ name: "image", label: "Image File", type: "text" }],
    commandTemplate: "foremost -i {{image}}",
  },
  {
    id: "testdisk",
    name: "TestDisk",
    category: "forensics",
    risk: "passiv",
    description: "Partition recovery and repair",
    executionMode: "external",
    inputFields: [{ name: "device", label: "Device Path", type: "text" }],
  },
  {
    id: "photorec",
    name: "PhotoRec",
    category: "forensics",
    risk: "passiv",
    description: "File recovery from deleted data",
    executionMode: "external",
    inputFields: [{ name: "device", label: "Device Path", type: "text" }],
  },
  {
    id: "hashpump",
    name: "Hashpump",
    category: "forensics",
    risk: "passiv",
    description: "Hash length extension attack tool",
    executionMode: "command-reference",
    inputFields: [{ name: "hash", label: "Hash Value", type: "text" }],
    commandTemplate: "hashpump -s {{hash}}",
  },
  {
    id: "xxd",
    name: "Xxd",
    category: "forensics",
    risk: "passiv",
    description: "Hexdump and binary file viewer",
    executionMode: "command-reference",
    inputFields: [{ name: "file", label: "File Path", type: "text" }],
    commandTemplate: "xxd {{file}}",
  },
  {
    id: "file",
    name: "File",
    category: "forensics",
    risk: "passiv",
    description: "File type identification",
    executionMode: "command-reference",
    inputFields: [{ name: "file", label: "File Path", type: "text" }],
    commandTemplate: "file {{file}}",
  },
  {
    id: "scalpel",
    name: "Scalpel",
    category: "forensics",
    risk: "passiv",
    description: "Forensic file carving tool",
    executionMode: "command-reference",
    inputFields: [{ name: "image", label: "Image File", type: "text" }],
    commandTemplate: "scalpel -i {{image}}",
  },
  {
    id: "bulk-extractor",
    name: "Bulk Extractor",
    category: "forensics",
    risk: "passiv",
    description: "Bulk data extraction from images",
    executionMode: "command-reference",
    inputFields: [{ name: "image", label: "Image File", type: "text" }],
    commandTemplate: "bulk_extractor {{image}}",
  },
  {
    id: "stegsolve",
    name: "Stegsolve",
    category: "forensics",
    risk: "passiv",
    description: "Image steganography solver",
    executionMode: "external",
    inputFields: [{ name: "image", label: "Image Path", type: "text" }],
  },
  {
    id: "zsteg",
    name: "Zsteg",
    category: "forensics",
    risk: "passiv",
    description: "PNG/BMP steganography detection",
    executionMode: "command-reference",
    inputFields: [{ name: "image", label: "Image Path", type: "text" }],
    commandTemplate: "zsteg {{image}}",
  },
  {
    id: "outguess",
    name: "Outguess",
    category: "forensics",
    risk: "passiv",
    description: "Steganographic data hiding and detection",
    executionMode: "command-reference",
    inputFields: [{ name: "file", label: "File Path", type: "text" }],
    commandTemplate: "outguess -r {{file}}",
  },
  {
    id: "sleuthkit",
    name: "SleuthKit",
    category: "forensics",
    risk: "passiv",
    description: "Forensic analysis framework",
    executionMode: "command-reference",
    inputFields: [{ name: "image", label: "Image File", type: "text" }],
    commandTemplate: "fls {{image}}",
  },
  {
    id: "autopsy",
    name: "Autopsy",
    category: "forensics",
    risk: "passiv",
    description: "Digital forensics platform",
    executionMode: "external",
    inputFields: [{ name: "case", label: "Case Name", type: "text" }],
  },

  // ========== CLOUD & CONTAINER SECURITY TOOLS (10 Tools) ==========
  {
    id: "prowler",
    name: "Prowler",
    category: "cloud",
    risk: "passiv",
    description: "AWS security assessment framework",
    executionMode: "command-reference",
    inputFields: [{ name: "profile", label: "AWS Profile", type: "text" }],
    commandTemplate: "prowler -p {{profile}}",
  },
  {
    id: "scout-suite",
    name: "Scout Suite",
    category: "cloud",
    risk: "passiv",
    description: "Multi-cloud security auditing tool",
    executionMode: "command-reference",
    inputFields: [{ name: "provider", label: "Cloud Provider", type: "select", options: ["aws", "azure", "gcp"] }],
    commandTemplate: "scout {{provider}}",
  },
  {
    id: "trivy",
    name: "Trivy",
    category: "cloud",
    risk: "passiv",
    description: "Container and image vulnerability scanner",
    executionMode: "command-reference",
    inputFields: [{ name: "image", label: "Container Image", type: "text" }],
    commandTemplate: "trivy image {{image}}",
  },
  {
    id: "kube-hunter",
    name: "Kube-Hunter",
    category: "cloud",
    risk: "kontrolliert",
    description: "Kubernetes cluster vulnerability scanner",
    executionMode: "command-reference",
    inputFields: [{ name: "target", label: "Kubernetes API", type: "text" }],
    commandTemplate: "kube-hunter --pod --report html",
  },
  {
    id: "kube-bench",
    name: "Kube-Bench",
    category: "cloud",
    risk: "passiv",
    description: "Kubernetes CIS benchmark checker",
    executionMode: "command-reference",
    inputFields: [{ name: "config", label: "Config File", type: "text" }],
    commandTemplate: "kube-bench run",
  },
  {
    id: "docker-bench-security",
    name: "Docker Bench Security",
    category: "cloud",
    risk: "passiv",
    description: "Docker security best practices checker",
    executionMode: "command-reference",
    inputFields: [{ name: "container", label: "Container ID", type: "text" }],
    commandTemplate: "docker-bench-security",
  },
  {
    id: "checkov",
    name: "Checkov",
    category: "cloud",
    risk: "passiv",
    description: "Infrastructure-as-Code security scanner",
    executionMode: "command-reference",
    inputFields: [{ name: "path", label: "IaC File Path", type: "text" }],
    commandTemplate: "checkov -d {{path}}",
  },
  {
    id: "terrascan",
    name: "Terrascan",
    category: "cloud",
    risk: "passiv",
    description: "Terraform security scanner",
    executionMode: "command-reference",
    inputFields: [{ name: "path", label: "Terraform Path", type: "text" }],
    commandTemplate: "terrascan scan -d {{path}}",
  },
  {
    id: "falco",
    name: "Falco",
    category: "cloud",
    risk: "passiv",
    description: "Container runtime security monitoring",
    executionMode: "external",
    inputFields: [{ name: "config", label: "Config File", type: "text" }],
  },
  {
    id: "clair",
    name: "Clair",
    category: "cloud",
    risk: "passiv",
    description: "Container image vulnerability detection",
    executionMode: "external",
    inputFields: [{ name: "image", label: "Container Image", type: "text" }],
  },

  // ========== EXPLOITATION TOOLS (3 Tools) ==========
  {
    id: "metasploit",
    name: "Metasploit",
    category: "pentest",
    risk: "aktiv",
    description: "Exploitation framework",
    executionMode: "external",
    inputFields: [{ name: "target", label: "Target", type: "text" }],
  },
  {
    id: "exploit-db",
    name: "Exploit-DB",
    category: "pentest",
    risk: "passiv",
    description: "Exploit database search and retrieval",
    executionMode: "web-integrated",
    inputFields: [{ name: "query", label: "Search Query", type: "text" }],
  },
  {
    id: "searchsploit",
    name: "SearchSploit",
    category: "pentest",
    risk: "passiv",
    description: "Offline exploit database search",
    executionMode: "command-reference",
    inputFields: [{ name: "query", label: "Search Query", type: "text" }],
    commandTemplate: "searchsploit {{query}}",
  },

  // ========== API & UTILITY TOOLS (8 Tools) ==========
  {
    id: "curl",
    name: "Curl",
    category: "pentest",
    risk: "passiv",
    description: "HTTP client for API testing",
    executionMode: "command-reference",
    inputFields: [{ name: "url", label: "URL", type: "text" }],
    commandTemplate: "curl {{url}}",
  },
  {
    id: "httpie",
    name: "HTTPie",
    category: "pentest",
    risk: "passiv",
    description: "User-friendly HTTP client",
    executionMode: "command-reference",
    inputFields: [{ name: "url", label: "URL", type: "text" }],
    commandTemplate: "http {{url}}",
  },
  {
    id: "postman",
    name: "Postman",
    category: "pentest",
    risk: "passiv",
    description: "API development and testing platform",
    executionMode: "external",
    inputFields: [{ name: "collection", label: "Collection File", type: "text" }],
  },
  {
    id: "insomnia",
    name: "Insomnia",
    category: "pentest",
    risk: "passiv",
    description: "REST and GraphQL client",
    executionMode: "external",
    inputFields: [{ name: "workspace", label: "Workspace", type: "text" }],
  },
  {
    id: "anew",
    name: "Anew",
    category: "pentest",
    risk: "passiv",
    description: "Append new lines to files efficiently",
    executionMode: "command-reference",
    inputFields: [{ name: "file", label: "File Path", type: "text" }],
    commandTemplate: "anew {{file}}",
  },
  {
    id: "qsreplace",
    name: "QSReplace",
    category: "pentest",
    risk: "passiv",
    description: "Query string parameter replacement",
    executionMode: "command-reference",
    inputFields: [{ name: "value", label: "Replacement Value", type: "text" }],
    commandTemplate: "qsreplace {{value}}",
  },
  {
    id: "uro",
    name: "Uro",
    category: "pentest",
    risk: "passiv",
    description: "URL filtering and deduplication",
    executionMode: "command-reference",
    inputFields: [{ name: "file", label: "URL File", type: "text" }],
    commandTemplate: "uro -i {{file}}",
  },
  {
    id: "whatweb",
    name: "WhatWeb",
    category: "pentest",
    risk: "passiv",
    description: "Web technology identification",
    executionMode: "command-reference",
    inputFields: [{ name: "url", label: "Target URL", type: "text" }],
    commandTemplate: "whatweb {{url}}",
  },

  // ========== WIRELESS & NETWORK TOOLS (4 Tools) ==========
  {
    id: "kismet",
    name: "Kismet",
    category: "recon",
    risk: "kontrolliert",
    description: "Wireless network detector and sniffer",
    executionMode: "external",
    inputFields: [{ name: "interface", label: "Interface", type: "text" }],
  },
  {
    id: "wireshark",
    name: "Wireshark",
    category: "recon",
    risk: "passiv",
    description: "Network packet analyzer",
    executionMode: "external",
    inputFields: [{ name: "interface", label: "Interface", type: "text" }],
  },
  {
    id: "tshark",
    name: "Tshark",
    category: "recon",
    risk: "passiv",
    description: "Command-line packet capture and analysis",
    executionMode: "command-reference",
    inputFields: [{ name: "interface", label: "Interface", type: "text" }],
    commandTemplate: "tshark -i {{interface}}",
  },
  {
    id: "tcpdump",
    name: "Tcpdump",
    category: "recon",
    risk: "passiv",
    description: "Network traffic capture tool",
    executionMode: "command-reference",
    inputFields: [{ name: "interface", label: "Interface", type: "text" }],
    commandTemplate: "tcpdump -i {{interface}}",
  },

  // ========== ADDITIONAL TOOLS (14 Tools) ==========
  {
    id: "smbmap",
    name: "SMBMap",
    category: "recon",
    risk: "kontrolliert",
    description: "SMB share enumeration and exploitation",
    executionMode: "command-reference",
    inputFields: [{ name: "host", label: "Target Host", type: "text" }],
    commandTemplate: "smbmap -H {{host}}",
  },
  {
    id: "evil-winrm",
    name: "Evil-WinRM",
    category: "pentest",
    risk: "aktiv",
    description: "Windows Remote Management exploitation",
    executionMode: "command-reference",
    inputFields: [{ name: "target", label: "Target Host", type: "text" }],
    commandTemplate: "evil-winrm -i {{target}}",
  },
  {
    id: "airmon-ng",
    name: "Airmon-ng",
    category: "recon",
    risk: "kontrolliert",
    description: "Wireless interface monitor mode enabler",
    executionMode: "command-reference",
    inputFields: [{ name: "interface", label: "Interface", type: "text" }],
    commandTemplate: "airmon-ng start {{interface}}",
  },
  {
    id: "airodump-ng",
    name: "Airodump-ng",
    category: "recon",
    risk: "kontrolliert",
    description: "WiFi network discovery and monitoring",
    executionMode: "command-reference",
    inputFields: [{ name: "interface", label: "Interface", type: "text" }],
    commandTemplate: "airodump-ng {{interface}}",
  },
  {
    id: "aireplay-ng",
    name: "Aireplay-ng",
    category: "pentest",
    risk: "aktiv",
    description: "WiFi attack and injection tool",
    executionMode: "external",
    inputFields: [{ name: "interface", label: "Interface", type: "text" }],
  },
  {
    id: "aircrack-ng",
    name: "Aircrack-ng",
    category: "pentest",
    risk: "aktiv",
    description: "WiFi security auditing suite",
    executionMode: "command-reference",
    inputFields: [{ name: "capfile", label: "Capture File", type: "text" }],
    commandTemplate: "aircrack-ng {{capfile}}",
  },
  {
    id: "msfvenom",
    name: "Msfvenom",
    category: "pentest",
    risk: "aktiv",
    description: "Payload generation framework",
    executionMode: "command-reference",
    inputFields: [{ name: "payload", label: "Payload Type", type: "text" }],
    commandTemplate: "msfvenom -p {{payload}}",
  },
  {
    id: "msfconsole",
    name: "Msfconsole",
    category: "pentest",
    risk: "aktiv",
    description: "Metasploit console interface",
    executionMode: "external",
    inputFields: [{ name: "resource", label: "Resource Script", type: "text" }],
  },
  {
    id: "rpcclient",
    name: "RPCClient",
    category: "recon",
    risk: "kontrolliert",
    description: "RPC enumeration and null session testing",
    executionMode: "command-reference",
    inputFields: [{ name: "host", label: "Target Host", type: "text" }],
    commandTemplate: "rpcclient -U '' {{host}}",
  },
  {
    id: "hash-identifier",
    name: "Hash-Identifier",
    category: "pentest",
    risk: "passiv",
    description: "Hash type identification",
    executionMode: "command-reference",
    inputFields: [{ name: "hash", label: "Hash Value", type: "text" }],
    commandTemplate: "hash-identifier {{hash}}",
  },
  {
    id: "ophcrack",
    name: "Ophcrack",
    category: "pentest",
    risk: "passiv",
    description: "Windows password cracker",
    executionMode: "external",
    inputFields: [{ name: "hashfile", label: "Hash File", type: "text" }],
  },
  {
    id: "dotdotpwn",
    name: "DotDotPwn",
    category: "pentest",
    risk: "kontrolliert",
    description: "Directory traversal vulnerability scanner",
    executionMode: "command-reference",
    inputFields: [{ name: "url", label: "Target URL", type: "text" }],
    commandTemplate: "dotdotpwn -m http -h {{url}}",
  },
  {
    id: "xsser",
    name: "XSSer",
    category: "pentest",
    risk: "kontrolliert",
    description: "Cross-Site Scripting vulnerability scanner",
    executionMode: "command-reference",
    inputFields: [{ name: "url", label: "Target URL", type: "text" }],
    commandTemplate: "xsser -u {{url}}",
  },
  {
    id: "wfuzz",
    name: "Wfuzz",
    category: "pentest",
    risk: "kontrolliert",
    description: "Web fuzzer for parameter discovery",
    executionMode: "command-reference",
    inputFields: [{ name: "url", label: "Target URL", type: "text" }],
    commandTemplate: "wfuzz -u {{url}} -w wordlist.txt",
  },
];

export const toolsByCategory = {
  osint: toolCatalog.filter((tool) => tool.category === "osint"),
  pentest: toolCatalog.filter((tool) => tool.category === "pentest"),
  recon: toolCatalog.filter((tool) => tool.category === "recon"),
  cloud: toolCatalog.filter((tool) => tool.category === "cloud"),
  forensics: toolCatalog.filter((tool) => tool.category === "forensics"),
  binary: toolCatalog.filter((tool) => tool.category === "binary"),
};

export const defaultSettings = {
  mode: "advisor-controlled",
  routing: "segmented-workspaces",
  logRetention: 30,
  rateProfile: "balanced",
  alerts: true,
  evidenceSnapshots: true,
};

export const assetUrls = {
  heroReference:
    "https://d2xsxph8kpxj0f.cloudfront.net/310519663552661904/XNBpKyMBuA4rXy2AbmJ3JH/cyber-control-room-reference-YuiGUiu5E8SwHPBbxaxfTj.webp",
  earth:
    "https://d2xsxph8kpxj0f.cloudfront.net/310519663552661904/XNBpKyMBuA4rXy2AbmJ3JH/cyber-earth-core-5Qav3BvyDf2yAtd4zZwSEy.webp",
  krockodogLogo:
    "https://d2xsxph8kpxj0f.cloudfront.net/310519663552661904/XNBpKyMBuA4rXy2AbmJ3JH/krockodog-frontpage-logo-dXLNrmhcavSYdiUsvafheK.webp",
};

export function categoryLabel(category: ToolCategory) {
  if (category === "osint") return "OSINT";
  if (category === "pentest") return "Pentest";
  if (category === "recon") return "Reconnaissance";
  if (category === "cloud") return "Cloud Security";
  if (category === "forensics") return "Forensics";
  return "Binary Analysis";
}

export function riskLabel(risk: ToolRisk) {
  if (risk === "passiv") return "Passiv";
  if (risk === "kontrolliert") return "Kontrolliert";
  return "Aktiv";
}

export function riskColor(risk: ToolRisk) {
  if (risk === "passiv") return "text-green-400";
  if (risk === "kontrolliert") return "text-yellow-400";
  return "text-red-400";
}
